use QuanLyDETAI

--Q58 Cho biết tên giáo viên nào mà tham gia đề tài đủ tất cả các chủ đề
-- EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT CD.MACD
					FROM CHUDE CD
					EXCEPT ( SELECT DT.MACD
							FROM THAMGIADT TG,DETAI DT
							WHERE GV.MAGV=TG.MAGV AND TG.MADT =DT.MADT ))
--NOT EXISTS 
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT *
					FROM CHUDE CD
					WHERE NOT EXISTS ( SELECT *
							FROM THAMGIADT TG,DETAI DT
							WHERE GV.MAGV=TG.MAGV AND TG.MADT =DT.MADT AND DT.MACD=CD.MACD))	
--COUNT 

SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE GV.MAGV =TG.MAGV AND TG.MADT= DT.MADT
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MACD) = ( SELECT COUNT(*)
									FROM CHUDE)




--Q59 Cho biết tên đề tài nào mà được tất cả các giáo viên của bộ môn HTTT tham gia
-- EXCEPT

SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT GV.MAGV
					FROM GIAOVIEN GV
					WHERE GV.MABM='HTTT'
					EXCEPT 
					SELECT	TG.MAGV
					FROM	THAMGIADT TG
					WHERE TG.MADT=DT.MADT)

--NOT EXISTS 
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT *
					FROM GIAOVIEN GV
					WHERE GV.MABM='HTTT'
					AND NOT EXISTS ( 
					SELECT	*
					FROM	THAMGIADT TG
					WHERE TG.MADT=DT.MADT and TG.MAGV=GV.MAGV))

--COUNT 
SELECT DT.TENDT
FROM DETAI DT, GIAOVIEN GV, THAMGIADT TG 
WHERE TG.MAGV=GV.MAGV AND TG.MADT = DT.MADT AND GV.MABM ='HTTT'
GROUP BY DT.TENDT
HAVING COUNT(DISTINCT GV.MAGV ) = ( SELECT COUNT(*) 
									FROM GIAOVIEN 
									WHERE GIAOVIEN.MABM='HTTT')


--Q60 Cho biết tên đề tài có tất cả giảng viên bộ môn “Hệ thống thông tin” tham gia
--EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ( SELECT GV.MAGV
					FROM GIAOVIEN GV, BOMON BM
					WHERE GV.MABM = BM.MABM AND BM.TENBM=N'Hệ thống thông tin'
					EXCEPT 
					SELECT TG.MAGV
					FROM THAMGIADT TG
					WHERE TG.MADT=DT.MADT )

--NOT EXISTS 

SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ( SELECT *
					FROM GIAOVIEN GV, BOMON BM
					WHERE GV.MABM = BM.MABM AND BM.TENBM=N'Hệ thống thông tin'
					AND NOT EXISTS ( 
					SELECT TG.MAGV
					FROM THAMGIADT TG
					WHERE TG.MADT=DT.MADT AND TG.MAGV=GV.MAGV))

--COUNT 

SELECT DT.TENDT
FROM DETAI DT,THAMGIADT TG, GIAOVIEN GV,BOMON BM
WHERE TG.MADT=DT.MADT AND TG.MAGV=GV.MAGV AND GV.MABM = BM.MABM AND BM.TENBM=N'Hệ thống thông tin'
GROUP BY DT.TENDT
HAVING COUNT(DISTINCT TG.MAGV) = (SELECT COUNT(*)
									FROM GIAOVIEN , BOMON
									WHERE GIAOVIEN.MABM = BOMON.MABM  AND BOMON.TENBM=N'Hệ thống thông tin')


--Q61 Cho biết giáo viên nào đã tham gia tất cả các đề tài có mã chủ đề là QLGD.
--EXCEPT
SELECT *
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT DT.MADT
					FROM  DETAI DT
					WHERE DT.MACD='QLGD'
					EXCEPT	
					SELECT TG.MADT
					FROM THAMGIADT TG
					WHERE TG.MAGV=GV.MAGV)
--NOT EXISTS 
SELECT *
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT *
					FROM  DETAI DT
					WHERE DT.MACD='QLGD'
					AND NOT EXISTS 
					(SELECT *
					FROM THAMGIADT TG
					WHERE TG.MAGV=GV.MAGV AND TG.MADT=DT.MADT))
-- COUNT 
SELECT GV.MAGV, COUNT(DISTINCT TG.MADT)
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE GV.MAGV= TG.MAGV AND TG.MADT = DT.MADT AND DT.MACD='QLGD'
GROUP BY GV.MAGV
HAVING COUNT(DISTINCT DT.MADT) =(SELECT COUNT(*)
									FROM DETAI
									WHERE DETAI.MACD='QLGD')

--Q62 Cho biết tên giáo viên nào tham gia tất cả các đề tài mà giáo viên Trần Trà Hương đã tham gia.
--EXCEPT 
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT TG.MADT
					FROM THAMGIADT TG, GIAOVIEN GV
					WHERE TG.MAGV=GV.MAGV AND GV.HOTEN =N'Trần Trà Hương'
					EXCEPT 
					SELECT TG2.MADT
					FROM THAMGIADT TG2
					WHERE TG2.MAGV = GV.MAGV) AND GV.HOTEN NOT LIKE N'Trần Trà Hương'
--NOT EXISTS 
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT *
					FROM THAMGIADT TG, GIAOVIEN GV2
					WHERE TG.MAGV=GV2.MAGV AND GV2.HOTEN =N'Trần Trà Hương'
					AND NOT EXISTS ( 
					SELECT *
					FROM THAMGIADT TG2
					WHERE TG2.MAGV = GV.MAGV AND TG2.MADT=TG.MADT)) AND GV.HOTEN NOT LIKE N'Trần Trà Hương'
--COUNT

SELECT GV.HOTEN
FROM GIAOVIEN GV , THAMGIADT TG
WHERE GV.MAGV = TG.MAGV
AND TG.MADT IN ( SELECT THAMGIADT.MADT
					FROM THAMGIADT, GIAOVIEN
					WHERE GIAOVIEN.HOTEN =N'Trần Trà Hương'AND THAMGIADT.MAGV=GIAOVIEN.MAGV)
GROUP BY GV.MAGV,GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) =(SELECT COUNT(DISTINCT THAMGIADT.MADT)
					FROM THAMGIADT, GIAOVIEN
					WHERE GIAOVIEN.HOTEN =N'Trần Trà Hương'AND THAMGIADT.MAGV=GIAOVIEN.MAGV) AND GV.HOTEN NOT LIKE N'Trần Trà Hương'

--Q63 Cho biết tên đề tài nào mà được tất cả các giáo viên của bộ môn Hóa Hữu Cơ tham gia.
--EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ( SELECT GV.MAGV
					FROM GIAOVIEN GV, BOMON BM
					WHERE GV.MABM=BM.MABM AND BM.TENBM =N'Hoá hữu cơ'
					EXCEPT
					SELECT TG.MAGV
					 FROM THAMGIADT TG
					WHERE TG.MADT= DT.MADT ) 

--NOT EXISTS 
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ( SELECT *
					FROM GIAOVIEN GV, BOMON BM
					WHERE GV.MABM=BM.MABM AND BM.TENBM =N'Hoá hữu cơ'
					AND NOT EXISTS (
					SELECT *
					 FROM THAMGIADT TG
					WHERE TG.MADT= DT.MADT AND TG.MAGV=GV.MAGV) )

--COUNT 
SELECT DT.TENDT
FROM DETAI DT,THAMGIADT TG, GIAOVIEN GV, BOMON BM
WHERE TG.MAGV=GV.MAGV AND TG.MADT = DT.MADT	 AND GV.MABM=BM.MABM AND BM.TENBM=N'Hoá hữu cơ'
GROUP BY DT.TENDT
HAVING COUNT(DISTINCT  GV.MAGV) =(  SELECT COUNT(*)
					FROM GIAOVIEN GV, BOMON BM
					WHERE GV.MABM=BM.MABM AND BM.TENBM =N'Hoá hữu cơ')

--Q64 Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài 006.
--EXCEPT 
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT CV.STT
					FROM CONGVIEC CV
					WHERE CV.MADT ='006'
					EXCEPT 
					SELECT TG.STT
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV AND TG.MADT='006')

--NOT EXISTS 

SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT *
					FROM CONGVIEC CV
					WHERE CV.MADT ='006'
					AND NOT EXISTS ( 
					SELECT *
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV AND CV.MADT=TG.MADT AND CV.STT = TG.STT))

--COUNT 
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV AND TG.MADT ='006'
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT TG.STT) = (SELECT COUNT(*)
					FROM CONGVIEC CV
					WHERE CV.MADT ='006') 

--Q65
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT DT.MADT
				   FROM DETAI DT, CHUDE CD
				   WHERE DT.MACD = CD.MACD AND CD.TENCD = N'Ứng dụng công nghệ'
				   EXCEPT
				   SELECT TG.MADT
				   FROM THAMGIADT TG
				   WHERE TG.MAGV = GV.MAGV )

--NOT EXISTS
SELECT GV.HOTEN
FROM	GIAOVIEN GV
WHERE NOT EXISTS (  SELECT *
					FROM DETAI DT, CHUDE CD
					WHERE DT.MACD = CD.MACD AND CD.TENCD =N'Ứng dụng công nghệ'
					AND NOT EXISTS ( 
					SELECT *
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))
--COUNT 
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT,CHUDE CD
WHERE GV.MAGV =TG.MAGV AND TG.MADT = DT.MADT AND DT.MACD=CD.MACD AND CD.TENCD =N'Ứng dụng công nghệ'
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT DT.MADT) = ( SELECT COUNT(*)
								   FROM DETAI DT, CHUDE CD
								   WHERE DT.MACD = CD.MACD AND CD.TENCD =N'Ứng dụng công nghệ')

--Q66 Cho biết tên giáo viên nào đã tham gia tất cả các đề tài của do Trần Trà Hương làm chủ nhiệm.
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT DT.MADT
				   FROM DETAI DT
				   JOIN GIAOVIEN GV2 ON DT.GVCNDT = GV2.MAGV AND GV2.HOTEN = N'Trần Trà Hương'
				   EXCEPT 
				   SELECT TG.MADT
				   FROM THAMGIADT TG
				   WHERE TG.MAGV = GV.MAGV)

--NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT *
				   FROM DETAI DT
				   JOIN GIAOVIEN GV2 ON DT.GVCNDT = GV2.MAGV AND GV2.HOTEN = N'Trần Trà Hương'
				   AND NOT EXISTS
				   (SELECT *
				   FROM THAMGIADT TG
				   WHERE TG.MAGV = GV.MAGV AND DT.MADT = TG.MADT))

--COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV
JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
JOIN DETAI DT ON DT.MADT = TG.MADT
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT (DISTINCT DT.MADT) = ( SELECT COUNT(*)
									FROM DETAI DT2
									JOIN GIAOVIEN GV2 ON GV2.MAGV =DT2.GVCNDT 
									WHERE GV2.HOTEN =N'Trần Trà Hương' )

--Q67 Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa CNTT tham gia
--EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ( SELECT GV.MAGV
					FROM GIAOVIEN GV
					JOIN BOMON BM ON GV.MABM = BM.MABM
					JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
					WHERE K.MAKHOA = 'CNTT'
					EXCEPT 
					SELECT GV2.MAGV
					FROM GIAOVIEN GV2
					JOIN THAMGIADT TG ON TG.MAGV = GV2.MAGV
					WHERE TG.MADT = DT.MADT )

--NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ( SELECT *
					FROM GIAOVIEN GV
					JOIN BOMON BM ON GV.MABM = BM.MABM
					JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
					WHERE K.MAKHOA = 'CNTT'
					AND NOT EXISTS (
					SELECT *
					FROM THAMGIADT TG
					WHERE TG.MADT = DT.MADT AND TG.MAGV=GV.MAGV ))

--COUNT
SELECT DT.TENDT
FROM DETAI DT
JOIN THAMGIADT TG ON DT.MADT = TG.MADT
JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
JOIN BOMON BM ON BM.MABM = GV.MABM
JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
WHERE K.MAKHOA = 'CNTT'
GROUP BY DT.TENDT, DT.MADT
HAVING COUNT(DISTINCT GV.MAGV) = ( SELECT COUNT(*)
								   FROM GIAOVIEN GV2
								   JOIN BOMON BM2 ON BM2.MABM = GV2.MABM
								   JOIN KHOA K2 ON K2.MAKHOA = BM2.MAKHOA
								   WHERE K.MAKHOA = 'CNTT')

--Q68 Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài Nghiên cứu tế bào gốc
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT CV.STT
				   FROM CONGVIEC CV
				   JOIN DETAI DT ON DT.MADT = CV.MADT 
				   WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
				   EXCEPT 
				   SELECT TG.STT
				   FROM THAMGIADT TG 
				   JOIN DETAI DT2 ON TG.MADT = DT2.MADT
				   WHERE TG.MAGV = GV.MAGV AND DT2.TENDT = N'Nghiên cứu tế bào gốc')

--NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT *
				   FROM CONGVIEC CV
				   JOIN DETAI DT ON DT.MADT = CV.MADT 
				   WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
				   AND NOT EXISTS( 
				   SELECT *
				   FROM THAMGIADT TG 
				   WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT AND TG.STT = CV.STT))

--COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV
JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
JOIN DETAI DT ON TG.MADT = DT.MADT
JOIN CONGVIEC CV ON CV.STT = TG.STT
WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT CV.STT) = ( SELECT COUNT(*) 
								  FROM CONGVIEC CV
								  JOIN DETAI DT ON DT.MADT = CV.MADT
								  WHERE DT.TENDT = N'Nghiên cứu tế bào gốc')  

--Q69 Tìm tên các giáo viên được phân công làm tất cả các đề tài có kinh phí trên 100 triệu?
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT DT.MADT
				   FROM DETAI DT
				   WHERE DT.KINHPHI > 100.0
				   EXCEPT 
				   SELECT TG.MADT
				   FROM THAMGIADT TG
				   WHERE TG.MAGV = GV.MAGV) 

--NOT EXISTS 
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT * 
				   FROM DETAI DT
				   WHERE DT.KINHPHI > 100
				   AND NOT EXISTS (
				   SELECT *
				   FROM THAMGIADT TG 
				   WHERE TG.MAGV = GV.MAGV AND DT.MADT = TG.MADT))

--COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV
JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
JOIN DETAI DT ON DT.MADT = TG.MADT
WHERE DT.KINHPHI > 100
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT DT.MADT) = ( SELECT COUNT(*)
								   FROM DETAI DT
								   WHERE DT.KINHPHI > 100.0)

--Q70 Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa Sinh Học tham gia
--EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ( SELECT GV.MAGV
				   FROM GIAOVIEN GV
				   JOIN BOMON BM ON BM.MABM = GV.MABM
				   JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
				   WHERE K.TENKHOA =N'SINH HỌC'
				   EXCEPT 
				   SELECT TG.MAGV
				   FROM THAMGIADT TG
				   WHERE TG.MADT =  DT.MADT )

--NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ( SELECT GV.MAGV
				   FROM GIAOVIEN GV
				   JOIN BOMON BM ON BM.MABM = GV.MABM
				   JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
				   WHERE K.TENKHOA =N'SINH HỌC'
				   AND NOT EXISTS ( 
				   SELECT TG.MAGV
				   FROM THAMGIADT TG
				   WHERE TG.MADT =  DT.MADT AND TG.MAGV = GV.MAGV))

--COUNT
SELECT DT.TENDT
FROM DETAI DT
JOIN THAMGIADT TG ON TG.MADT = DT.MADT
JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
JOIN BOMON BM ON BM.MABM = GV.MABM
JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
WHERE K.TENKHOA =N'SINH HỌC'
GROUP BY DT.TENDT, DT.MADT
HAVING COUNT(DISTINCT GV.MAGV) = ( SELECT COUNT(GV.MAGV)
								   FROM GIAOVIEN GV
								   JOIN BOMON BM ON BM.MABM = GV.MABM
								   JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
								   WHERE K.TENKHOA =N'SINH HỌC')

--Q71 Cho biết mã số, họ tên, ngày sinh của giáo viên tham gia tất cả các công việc của đề tài “Ứng dụng hóa học xanh”
--EXCEPT
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT CV.MADT
				   FROM DETAI DT 
				   JOIN CONGVIEC CV ON CV.MADT = DT.MADT
				   WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
				   EXCEPT 
				   SELECT TG.MADT
				   FROM THAMGIADT TG
				   JOIN DETAI DT2 ON TG.MADT = DT2.MADT
				   WHERE TG.MAGV = GV.MAGV AND DT2.TENDT = N'Ứng dụng hóa học xanh')

--NOT EXISTS
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT CV.MADT
				   FROM DETAI DT 
				   JOIN CONGVIEC CV ON CV.MADT = DT.MADT
				   WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
				   AND NOT EXISTS (
				   SELECT TG.MADT
				   FROM THAMGIADT TG
				   WHERE TG.MAGV = GV.MAGV AND DT.TENDT = N'Ứng dụng hóa học xanh'))

--COUNT
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV
JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
JOIN DETAI DT ON DT.MADT = TG.MADT
JOIN CONGVIEC CV ON CV.MADT = DT.MADT 
WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
GROUP BY GV.MAGV, GV.HOTEN, GV.NGSINH
HAVING COUNT(DISTINCT CV.STT ) = ( SELECT COUNT(CV.STT)
									FROM CONGVIEC CV
									JOIN DETAI DT2 ON DT2.MADT = CV.MADT
									WHERE DT2.TENDT = N'Ứng dụng hóa học xanh' )


--Q72 Cho biết mã số, họ tên, tên bộ môn và tên người quản lý chuyên môn của giáo viên tham gia tất cả các đề tài thuộc chủ đề “Nghiên cứu phát triển”
-- EXCEPT 
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN AS GVQL
FROM GIAOVIEN GV
JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN GIAOVIEN GVQL ON GVQL.MAGV = GV.GVQLCM
WHERE NOT EXISTS (  SELECT DT.MADT
					FROM  DETAI DT
					JOIN CHUDE CD ON DT.MACD = CD.MACD 
					WHERE CD.TENCD =N'Nghiên cứu phát triển'
					EXCEPT 
					SELECT TG.MADT
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV )
-- NOT EXISTS
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN AS GVQL
FROM GIAOVIEN GV
JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN GIAOVIEN GVQL ON GVQL.MAGV = GV.GVQLCM
WHERE NOT EXISTS (  SELECT DT.MADT
					FROM  DETAI DT
					JOIN CHUDE CD ON DT.MACD = CD.MACD 
					WHERE CD.TENCD =N'Nghiên cứu phát triển'
					AND NOT EXISTS ( 
					SELECT TG.MADT
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV  AND DT.MADT = TG.MADT))			
-- COUNT 	

SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN AS GVQL
FROM GIAOVIEN GV
JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN GIAOVIEN GVQL ON GVQL.MAGV = GV.GVQLCM
JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
JOIN DETAI DT ON TG.MADT = DT.MADT
JOIN CHUDE CD ON CD.MACD = DT.MACD
WHERE CD.TENCD =N'Nghiên cứu phát triển'
GROUP BY GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN
HAVING COUNT( DISTINCT DT.MADT ) = ( SELECT COUNT(DT.MADT)
								     FROM  DETAI DT
									 JOIN CHUDE CD ON DT.MACD = CD.MACD 
									 WHERE CD.TENCD =N'Nghiên cứu phát triển')


