use QuanLyDETAI;

-- Q27 Cho biết số lượng giáo viên viên và tổng lương của họ
SELECT COUNT(*)  SLGV, SUM(LUONG)  TONG_LUONG
FROM GIAOVIEN

-- Q28 Cho biết số lượng giáo viên và lương trung bình của từng bộ môn
SELECT MABM, COUNT(*)  SLGV, AVG(LUONG)  LUONG_TB
FROM GIAOVIEN
GROUP BY MABM

-- Q29 Cho biết tên chủ đề và số lượng đề tài thuộc về chủ đề đó
SELECT CHUDE.TENCD, COUNT (DETAI.MADT)  SL_DT
FROM CHUDE LEFT JOIN DETAI ON CHUDE.MACD = DETAI.MACD
GROUP BY CHUDE.MACD, CHUDE.TENCD
 
-- Q30 Cho biết tên giáo viên và số lượng đề tài mà giáo viên đó tham gia
SELECT HOTEN, COUNT (DISTINCT THAMGIADT.MADT)  SL_DT
FROM GIAOVIEN LEFT JOIN THAMGIADT ON GIAOVIEN.MAGV = THAMGIADT.MAGV
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN

-- Q31 Cho biết tên giáo viên và số lượng đề tài mà giáo viên đó làm chủ nhiệm
SELECT HOTEN, COUNT (DETAI.GVCNDT)  SL_DT_CN
FROM GIAOVIEN LEFT JOIN DETAI ON GIAOVIEN.MAGV = DETAI.GVCNDT
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN

-- Q32 Với mỗi giáo viên cho tên giáo viên và số người thân của giáo viên đó
SELECT HOTEN, COUNT (NGUOITHAN.TEN) SONGUOITHAN
FROM GIAOVIEN LEFT JOIN NGUOITHAN ON GIAOVIEN.MAGV = NGUOITHAN.MAGV
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN

-- Q33 Cho biết tên những giáo viên đã tham gia từ 3 đề tài trở lên
SELECT GIAOVIEN.HOTEN
FROM GIAOVIEN, THAMGIADT
WHERE GIAOVIEN.MAGV = THAMGIADT.MAGV
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN
HAVING COUNT (DISTINCT THAMGIADT.MADT) >= 3

-- Q34 Cho biết số lượng giáo viên đã tham gia vào đề tài Ứng dụng hóa học xanh
SELECT COUNT(DISTINCT THAMGIADT.MAGV)  SLTGUDX
FROM DETAI, THAMGIADT
WHERE DETAI.TENDT = N'Ứng dụng hoá học xanh' AND DETAI.MADT = THAMGIADT.MADT
GROUP BY THAMGIADT.MADT